import fs from "fs";
import path from "path";

const BASE = process.cwd();

function write(filePath, content) {
  const full = path.join(BASE, filePath);
  const dir = path.dirname(full);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(full, content, "utf-8");
  console.log("OK:", filePath);
}

function ensureDir(dirPath) {
  const full = path.join(BASE, dirPath);
  if (!fs.existsSync(full)) fs.mkdirSync(full, { recursive: true });
}

// ─── 1. SCHEMA ───
write("src/convex/schema.ts", [
  'import { authTables } from "@convex-dev/auth/server";',
  'import { defineSchema, defineTable } from "convex/server";',
  'import { v } from "convex/values";',
  "",
  "export default defineSchema({",
  "  ...authTables,",
  "",
  "  adminAuth: defineTable({",
  '    username: v.string(),',
  '    passwordHash: v.string(),',
  '    salt: v.string(),',
  '    recoveryKey: v.optional(v.string()),',
  '    recoveryKeyHash: v.optional(v.string()),',
  '    failedLoginAttempts: v.optional(v.number()),',
  '    lockedUntil: v.optional(v.number()),',
  '    lastLoginAt: v.optional(v.number()),',
  '    lastLoginIp: v.optional(v.string()),',
  '    createdAt: v.number(),',
  '    updatedAt: v.number(),',
  '  }).index("username", ["username"]),',
  "",
  "  adminSessions: defineTable({",
  '    adminId: v.id("adminAuth"),',
  '    token: v.string(),',
  '    ipAddress: v.optional(v.string()),',
  '    userAgent: v.optional(v.string()),',
  '    expiresAt: v.number(),',
  '    createdAt: v.number(),',
  '  }).index("token", ["token"]),',
  "",
  "  adminAuditLogs: defineTable({",
  '    adminId: v.id("adminAuth"),',
  '    action: v.string(),',
  '    details: v.optional(v.string()),',
  '    ipAddress: v.optional(v.string()),',
  '    createdAt: v.number(),',
  '  }).index("adminId", ["adminId"]),',
  "",
  "  settings: defineTable({",
  '    key: v.string(),',
  '    value: v.any(),',
  '    updatedAt: v.number(),',
  '  }).index("key", ["key"]),',
  "",
  "  categories: defineTable({",
  '    name: v.string(),',
  '    slug: v.string(),',
  '    description: v.optional(v.string()),',
  '    image: v.optional(v.string()),',
  '    parentId: v.optional(v.id("categories")),',
  '    businessType: v.union(v.literal("kitchen"), v.literal("mart"), v.literal("both")),',
  '    displayOrder: v.number(),',
  '    isActive: v.boolean(),',
  '    createdAt: v.number(),',
  '    updatedAt: v.number(),',
  '  }).index("slug", ["slug"]).index("parentId", ["parentId"]).index("businessType", ["businessType"]).index("displayOrder", ["displayOrder"]),',
  "",
  "  products: defineTable({",
  '    name: v.string(),',
  '    slug: v.string(),',
  '    description: v.optional(v.string()),',
  '    images: v.array(v.string()),',
  '    categoryId: v.id("categories"),',
  '    businessType: v.union(v.literal("kitchen"), v.literal("mart")),',
  '    mrp: v.number(),',
  '    sellingPrice: v.number(),',
  '    discount: v.optional(v.number()),',
  '    sku: v.optional(v.string()),',
  '    stock: v.number(),',
  '    lowStockAlert: v.optional(v.number()),',
  '    displayOrder: v.number(),',
  '    isVeg: v.boolean(),',
  '    isBestSeller: v.optional(v.boolean()),',
  '    isNewArrival: v.optional(v.boolean()),',
  '    isOutOfStock: v.optional(v.boolean()),',
  '    weightValue: v.number(),',
  '    weightUnit: v.string(),',
  '    isActive: v.boolean(),',
  '    createdAt: v.number(),',
  '    updatedAt: v.number(),',
  '  }).index("slug", ["slug"]).index("categoryId", ["categoryId"]).index("businessType", ["businessType"]).index("displayOrder", ["displayOrder"]).index("isActive", ["isActive"]),',
  "",
  "  orders: defineTable({",
  '    orderNumber: v.string(), customerName: v.string(), customerPhone: v.string(),',
  '    customerEmail: v.optional(v.string()),',
  '    businessType: v.union(v.literal("kitchen"), v.literal("mart")),',
  '    orderType: v.union(v.literal("delivery"), v.literal("takeaway")),',
  '    items: v.array(v.object({ productId: v.id("products"), name: v.string(), quantity: v.number(), unitPrice: v.number(), totalPrice: v.number(), weight: v.optional(v.string()) })),',
  '    subtotal: v.number(),',
  '    deliveryCharge: v.optional(v.number()), packingCharge: v.optional(v.number()), tax: v.optional(v.number()),',
  '    total: v.number(),',
  '    status: v.union(v.literal("pending"), v.literal("confirmed"), v.literal("preparing"), v.literal("ready"), v.literal("out_for_delivery"), v.literal("delivered"), v.literal("cancelled")),',
  '    paymentMethod: v.union(v.literal("cod"), v.literal("upi")),',
  '    paymentStatus: v.union(v.literal("pending"), v.literal("paid"), v.literal("failed")),',
  '    upiTransactionId: v.optional(v.string()),',
  '    deliveryAddress: v.optional(v.object({ street: v.string(), city: v.string(), state: v.string(), pincode: v.string(), landmark: v.optional(v.string()) })),',
  '    notes: v.optional(v.string()),',
  '    createdAt: v.number(), updatedAt: v.number(),',
  '  }).index("orderNumber", ["orderNumber"]).index("status", ["status"]).index("createdAt", ["createdAt"]),',
  "",
  "  reviews: defineTable({",
  '    productId: v.id("products"), orderId: v.optional(v.id("orders")),',
  '    customerName: v.string(), customerPhone: v.string(),',
  '    rating: v.number(), comment: v.optional(v.string()),',
  '    isVerifiedPurchase: v.boolean(), isApproved: v.boolean(), createdAt: v.number(),',
  '  }).index("productId", ["productId"]),',
  "",
  "});",
].join("\n"));

// ─── 2. BACKEND FILES ───

// adminAuth.ts
write("src/convex/adminAuth.ts", [
  'import { v } from "convex/values";',
  'import { mutation, query } from "./_generated/server";',
  '',
  'const DEFAULT_USERNAME = "admin";',
  'const DEFAULT_PASSWORD = "Admin@123";',
  'const PBKDF2_ITERATIONS = 100000;',
  'const MAX_FAILED = 5;',
  'const LOCKOUT_MS = 15 * 60 * 1000;',
  'const SESSION_MS = 24 * 60 * 60 * 1000;',
  '',
  'function genSalt() { const chars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"; let s=""; const a=new Uint8Array(32); crypto.getRandomValues(a); for(let i=0;i<32;i++) s+=chars[a[i]%chars.length]; return s; }',
  'function genKey() { const chars="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"; const seg=[]; for(let s=0;s<4;s++){let seg2="";const a=new Uint8Array(4);crypto.getRandomValues(a);for(let i=0;i<4;i++)seg2+=chars[a[i]%chars.length];seg.push(seg2);}return seg.join("-");}',
  'function genToken() { const chars="abcdefghijklmnopqrstuvwxyz0123456789"; let t=""; const a=new Uint8Array(48); crypto.getRandomValues(a); for(let i=0;i<48;i++) t+=chars[a[i]%chars.length]; return t; }',
  '',
  'async function hashPw(pw, salt) {',
  '  const enc = new TextEncoder();',
  '  const km = await crypto.subtle.importKey("raw", enc.encode(pw), "PBKDF2", false, ["deriveBits"]);',
  '  const bits = await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(salt),iterations:PBKDF2_ITERATIONS,hash:"SHA-512"}, km, 512);',
  '  return Array.from(new Uint8Array(bits)).map(b=>b.toString(16).padStart(2,"0")).join("");',
  '}',
  '',
  'export const initializeAdmin = mutation({ args: {}, handler: async (ctx) => {',
  '  const ex = await ctx.db.query("adminAuth").withIndex("username", q=>q.eq("username",DEFAULT_USERNAME)).first();',
  '  if(ex) return {initialized:false};',
  '  const salt=genSalt(); const hash=await hashPw(DEFAULT_PASSWORD,salt); const rk=genKey(); const rkHash=await hashPw(rk,salt);',
  '  await ctx.db.insert("adminAuth",{username:DEFAULT_USERNAME,passwordHash:hash,salt,recoveryKey:rk,recoveryKeyHash:rkHash,failedLoginAttempts:0,createdAt:Date.now(),updatedAt:Date.now()});',
  '  return {initialized:true,recoveryKey:rk};',
  '}});',
  '',
  'export const verifyPassword = query({ args: {password: v.string()}, handler: async (ctx, args) => {',
  '  const a = await ctx.db.query("adminAuth").withIndex("username", q=>q.eq("username",DEFAULT_USERNAME)).first();',
  '  if(!a) return {valid:false};',
  '  if(a.lockedUntil && a.lockedUntil>Date.now()) return {valid:false, locked:true};',
  '  return {valid: (await hashPw(args.password, a.salt)) === a.passwordHash};',
  '}});',
  '',
  'export const login = mutation({ args: {password: v.string()}, handler: async (ctx, args) => {',
  '  const a = await ctx.db.query("adminAuth").withIndex("username", q=>q.eq("username",DEFAULT_USERNAME)).first();',
  '  if(!a) return {success:false,message:"Not found"};',
  '  const now=Date.now();',
  '  if(a.lockedUntil && a.lockedUntil>now) return {success:false,message:"Locked"};',
  '  if((await hashPw(args.password,a.salt))!==a.passwordHash) {',
  '    const f=(a.failedLoginAttempts||0)+1; const u={failedLoginAttempts:f,updatedAt:now};',
  '    if(f>=MAX_FAILED) u.lockedUntil=now+LOCKOUT_MS;',
  '    await ctx.db.patch(a._id,u);',
  '    return {success:false,message:`Invalid. ${MAX_FAILED-f} left`,attemptsRemaining:Math.max(0,MAX_FAILED-f)};',
  '  }',
  '  const token=genToken();',
  '  await ctx.db.patch(a._id,{failedLoginAttempts:0,lockedUntil:undefined,lastLoginAt:now,updatedAt:now});',
  '  await ctx.db.insert("adminSessions",{adminId:a._id,token,expiresAt:now+SESSION_MS,createdAt:now});',
  '  return {success:true,token,adminId:a._id};',
  '}});',
  '',
  'export const verifySession = query({ args: {token: v.string()}, handler: async (ctx, args) => {',
  '  const s = await ctx.db.query("adminSessions").withIndex("token", q=>q.eq("token",args.token)).first();',
  '  if(!s || s.expiresAt<Date.now()) return {valid:false};',
  '  return {valid:true};',
  '}});',
  '',
  'export const changePassword = mutation({ args: {currentPassword: v.string(), newPassword: v.string(), token: v.string()}, handler: async (ctx, args) => {',
  '  const s = await ctx.db.query("adminSessions").withIndex("token", q=>q.eq("token",args.token)).first();',
  '  if(!s||s.expiresAt<Date.now()) return {success:false,message:"Session expired"};',
  '  const a=await ctx.db.get(s.adminId); if(!a) return {success:false};',
  '  if((await hashPw(args.currentPassword,a.salt))!==a.passwordHash) return {success:false,message:"Wrong password"};',
  '  if(args.newPassword.length<6) return {success:false,message:"Min 6 chars"};',
  '  const ns=genSalt(); await ctx.db.patch(a._id,{passwordHash:await hashPw(args.newPassword,ns),salt:ns,updatedAt:Date.now()});',
  '  return {success:true};',
  '}});',
  '',
  'export const resetPasswordWithRecoveryKey = mutation({ args: {recoveryKey: v.string(), newPassword: v.string()}, handler: async (ctx, args) => {',
  '  const a = await ctx.db.query("adminAuth").withIndex("username", q=>q.eq("username",DEFAULT_USERNAME)).first();',
  '  if(!a||!a.recoveryKeyHash) return {success:false,message:"No key"};',
  '  if((await hashPw(args.recoveryKey.toUpperCase(),a.salt))!==a.recoveryKeyHash) return {success:false,message:"Invalid key"};',
  '  const ns=genSalt(); await ctx.db.patch(a._id,{passwordHash:await hashPw(args.newPassword,ns),salt:ns,failedLoginAttempts:0,lockedUntil:undefined,updatedAt:Date.now()});',
  '  return {success:true};',
  '}});',
  '',
  'export const getAdminInfo = query({ args: {token: v.string()}, handler: async (ctx, args) => {',
  '  const s = await ctx.db.query("adminSessions").withIndex("token", q=>q.eq("token",args.token)).first();',
  '  if(!s||s.expiresAt<Date.now()) return null;',
  '  const a=await ctx.db.get(s.adminId); if(!a) return null;',
  '  return {username:a.username,lastLoginAt:a.lastLoginAt,createdAt:a.createdAt};',
  '}});',
  '',
  'export const getAuditLogs = query({ args:{token:v.string(),limit:v.optional(v.number())}, handler:async(ctx,args)=>{',
  '  const s=await ctx.db.query("adminSessions").withIndex("token",q=>q.eq("token",args.token)).first();',
  '  if(!s) return [];',
  '  return (await ctx.db.query("adminAuditLogs").order("desc").take(args.limit||50)).map(l=>({action:l.action,details:l.details,createdAt:l.createdAt}));',
  '}});',
  '',
  'export const logout = mutation({ args:{token:v.string()}, handler:async(ctx,args)=>{',
  '  const s=await ctx.db.query("adminSessions").withIndex("token",q=>q.eq("token",args.token)).first();',
  '  if(s) await ctx.db.delete(s._id);',
  '}});',
].join("\n"));

// settings.ts
write("src/convex/settings.ts", [
  'import { v } from "convex/values";',
  'import { mutation, query } from "./_generated/server";',
  '',
  "const DEFAULTS = {",
  '  businessName: "MB Crunchy", businessTagline: "Fresh & Delicious",',
  '  businessEmail: "hello@mbcrunchy.com", businessPhone: "", businessAddress: "",',
  '  businessLogo: "", businessFavicon: "",',
  '  primaryColor: "#E85D2C", secondaryColor: "#F5A623", accentColor: "#2ECC71",',
  '  backgroundColor: "#FFF8F0", textColor: "#1A1A2E",',
  '  whatsappNumber: "", instagramUrl: "", facebookUrl: "", youtubeUrl: "", twitterUrl: "",',
  '  upiId: "", upiMerchantName: "MB Crunchy",',
  '  deliveryEnabled: true, takeawayEnabled: true, deliveryRadius: 10,',
  '  deliveryCharge: 30, freeDeliveryMinOrder: 200, estimatedDeliveryMinutes: 30,',
  '  openingTime: "09:00", closingTime: "22:00",',
  '  kitchenOpenDays: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],',
  '  martOpenDays: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],',
  '  taxRate: 5, taxName: "GST", packingCharge: 10,',
  "};",
  '',
  'export const getAll = query({ args: {}, handler: async (ctx) => {',
  '  const all = await ctx.db.query("settings").collect(); const r={...DEFAULTS};',
  '  for(const s of all) r[s.key]=s.value; return r;',
  '}});',
  '',
  'export const getBranding = query({ args: {}, handler: async (ctx) => {',
  '  const all = await ctx.db.query("settings").collect();',
  '  const keys=["businessName","businessTagline","businessLogo","businessFavicon","primaryColor","secondaryColor","accentColor","backgroundColor","textColor","whatsappNumber","instagramUrl","facebookUrl","youtubeUrl","twitterUrl","upiId","upiMerchantName","businessPhone","businessEmail","businessAddress"];',
  '  const r={}; for(const k of keys){const s=all.find(x=>x.key===k);r[k]=s?.value??DEFAULTS[k]??null;} return r;',
  '}});',
  '',
  'export const bulkUpdate = mutation({',
  '  args: {settings: v.array(v.object({key: v.string(), value: v.any()}))},',
  '  handler: async (ctx, args) => {',
  '    const now=Date.now();',
  '    for(const {key,value} of args.settings){',
  '      const ex=await ctx.db.query("settings").withIndex("key",q=>q.eq("key",key)).first();',
  '      if(ex) await ctx.db.patch(ex._id,{value,updatedAt:now});',
  '      else await ctx.db.insert("settings",{key,value,updatedAt:now});',
  '    }',
  '  },',
  '});',
  '',
  'export const getDeliverySettings = query({ args: {}, handler: async (ctx) => {',
  '  const all = await ctx.db.query("settings").collect();',
  '  const keys=["deliveryEnabled","takeawayEnabled","deliveryRadius","deliveryCharge","freeDeliveryMinOrder","estimatedDeliveryMinutes","maxDeliveryDistance","openingTime","closingTime"];',
  '  const r={}; for(const k of keys){const s=all.find(x=>x.key===k);r[k]=s?.value??DEFAULTS[k]??null;} return r;',
  '}});',
].join("\n"));

// categories.ts
write("src/convex/categories.ts", [
  'import { v } from "convex/values";',
  'import { mutation, query } from "./_generated/server";',
  '',
  'export const getAll = query({',
  '  args: {businessType: v.optional(v.union(v.literal("kitchen"),v.literal("mart"))), includeInactive: v.optional(v.boolean())},',
  '  handler: async (ctx, args) => {',
  '    let cats;',
  '    if(args.businessType) cats=await ctx.db.query("categories").withIndex("businessType",q=>q.eq("businessType",args.businessType)).collect();',
  '    else cats=await ctx.db.query("categories").collect();',
  '    if(!args.includeInactive) cats=cats.filter(c=>c.isActive);',
  '    return cats.sort((a,b)=>a.displayOrder-b.displayOrder);',
  '  },',
  '});',
  '',
  'export const create = mutation({',
  '  args: {name:v.string(),slug:v.string(),description:v.optional(v.string()),image:v.optional(v.string()),parentId:v.optional(v.id("categories")),businessType:v.union(v.literal("kitchen"),v.literal("mart"),v.literal("both")),displayOrder:v.optional(v.number()),isActive:v.optional(v.boolean())},',
  '  handler: async (ctx, args) => {',
  '    const all=await ctx.db.query("categories").collect();',
  '    const max=all.reduce((m,c)=>Math.max(m,c.displayOrder),0);',
  '    const id=await ctx.db.insert("categories",{name:args.name,slug:args.slug,description:args.description,image:args.image,parentId:args.parentId,businessType:args.businessType,displayOrder:args.displayOrder??max+1,isActive:args.isActive??true,createdAt:Date.now(),updatedAt:Date.now()});',
  '    return await ctx.db.get(id);',
  '  },',
  '});',
  '',
  'export const update = mutation({',
  '  args: {id:v.id("categories"),name:v.optional(v.string()),slug:v.optional(v.string()),description:v.optional(v.string()),image:v.optional(v.string()),parentId:v.optional(v.id("categories")),businessType:v.optional(v.union(v.literal("kitchen"),v.literal("mart"),v.literal("both"))),displayOrder:v.optional(v.number()),isActive:v.optional(v.boolean())},',
  '  handler: async (ctx, args) => {',
  '    const {id,...up}=args; const d={}; for(const[k,v]of Object.entries(up)){if(v!==undefined)d[k]=v;}',
  '    d.updatedAt=Date.now(); await ctx.db.patch(id,d); return await ctx.db.get(id);',
  '  },',
  '});',
  '',
  'export const remove = mutation({ args:{id:v.id("categories")}, handler:async(ctx,args)=>{',
  '  const c=await ctx.db.get(args.id); if(!c) return {success:false};',
  '  const kids=await ctx.db.query("categories").withIndex("parentId",q=>q.eq("parentId",args.id)).collect();',
  '  if(kids.length>0) return {success:false,message:`Has ${kids.length} subcategories`};',
  '  await ctx.db.delete(args.id); return {success:true};',
  '}});',
  '',
  'export const getStats = query({ args:{}, handler:async(ctx)=>{',
  '  const c=await ctx.db.query("categories").collect();',
  '  return {total:c.length,active:c.filter(x=>x.isActive).length,kitchen:c.filter(x=>x.businessType==="kitchen"||x.businessType==="both").length,mart:c.filter(x=>x.businessType==="mart"||x.businessType==="both").length};',
  '}});',
].join("\n"));

// products.ts
write("src/convex/products.ts", [
  'import { v } from "convex/values";',
  'import { mutation, query } from "./_generated/server";',
  '',
  'const VALID_UNITS=["gm","kg","ml","litre","pcs","piece","plate","pack","box","jar","bottle"];',
  '',
  'export const getAll = query({',
  '  args: {businessType:v.optional(v.union(v.literal("kitchen"),v.literal("mart"))),categoryId:v.optional(v.id("categories")),includeInactive:v.optional(v.boolean()),search:v.optional(v.string()),limit:v.optional(v.number()),offset:v.optional(v.number())},',
  '  handler: async (ctx, args) => {',
  '    let p;',
  '    if(args.businessType) p=await ctx.db.query("products").withIndex("businessType",q=>q.eq("businessType",args.businessType)).collect();',
  '    else p=await ctx.db.query("products").collect();',
  '    if(!args.includeInactive) p=p.filter(x=>x.isActive);',
  '    if(args.categoryId) p=p.filter(x=>x.categoryId===args.categoryId);',
  '    if(args.search){const q=args.search.toLowerCase();p=p.filter(x=>x.name.toLowerCase().includes(q)||x.description?.toLowerCase().includes(q));}',
  '    p.sort((a,b)=>a.displayOrder-b.displayOrder);',
  '    const total=p.length; const off=args.offset||0; const lim=args.limit||50;',
  '    return {products:p.slice(off,off+lim),total};',
  '  },',
  '});',
  '',
  'export const getById = query({args:{id:v.id("products")},handler:async(ctx,args)=>await ctx.db.get(args.id)});',
  '',
  'export const create = mutation({',
  '  args: {name:v.string(),slug:v.string(),description:v.optional(v.string()),images:v.array(v.string()),categoryId:v.id("categories"),businessType:v.union(v.literal("kitchen"),v.literal("mart")),mrp:v.number(),sellingPrice:v.number(),sku:v.optional(v.string()),stock:v.number(),lowStockAlert:v.optional(v.number()),displayOrder:v.optional(v.number()),isVeg:v.boolean(),isBestSeller:v.optional(v.boolean()),isNewArrival:v.optional(v.boolean()),isOutOfStock:v.optional(v.boolean()),weightValue:v.number(),weightUnit:v.string(),isActive:v.optional(v.boolean())},',
  '  handler: async (ctx, args) => {',
  '    if(!VALID_UNITS.includes(args.weightUnit)) throw new Error("Invalid unit");',
  '    const now=Date.now();',
  '    const id=await ctx.db.insert("products",{name:args.name,slug:args.slug,description:args.description,images:args.images,categoryId:args.categoryId,businessType:args.businessType,mrp:args.mrp,sellingPrice:args.sellingPrice,discount:Math.round((1-args.sellingPrice/args.mrp)*100),sku:args.sku,stock:args.stock,lowStockAlert:args.lowStockAlert,displayOrder:args.displayOrder??0,isVeg:args.isVeg,isBestSeller:args.isBestSeller,isNewArrival:args.isNewArrival,isOutOfStock:args.isOutOfStock,weightValue:args.weightValue,weightUnit:args.weightUnit,isActive:args.isActive??true,createdAt:now,updatedAt:now});',
  '    return await ctx.db.get(id);',
  '  },',
  '});',
  '',
  'export const update = mutation({',
  '  args: {id:v.id("products"),name:v.optional(v.string()),slug:v.optional(v.string()),description:v.optional(v.string()),images:v.optional(v.array(v.string())),categoryId:v.optional(v.id("categories")),businessType:v.optional(v.union(v.literal("kitchen"),v.literal("mart"))),mrp:v.optional(v.number()),sellingPrice:v.optional(v.number()),sku:v.optional(v.string()),stock:v.optional(v.number()),lowStockAlert:v.optional(v.number()),displayOrder:v.optional(v.number()),isVeg:v.optional(v.boolean()),isBestSeller:v.optional(v.boolean()),isNewArrival:v.optional(v.boolean()),isOutOfStock:v.optional(v.boolean()),weightValue:v.optional(v.number()),weightUnit:v.optional(v.string()),isActive:v.optional(v.boolean())},',
  '  handler: async (ctx, args) => {',
  '    const{id,...up}=args; const d={}; for(const[k,v]of Object.entries(up)){if(v!==undefined)d[k]=v;}',
  '    d.updatedAt=Date.now(); await ctx.db.patch(id,d); return await ctx.db.get(id);',
  '  },',
  '});',
  '',
  'export const remove = mutation({args:{id:v.id("products")},handler:async(ctx,args)=>{await ctx.db.delete(args.id);return{success:true};}});',
  '',
  'export const toggleActive = mutation({',
  '  args:{id:v.id("products")}, handler:async(ctx,args)=>{',
  '    const p=await ctx.db.get(args.id); if(!p) return{success:false};',
  '    await ctx.db.patch(args.id,{isActive:!p.isActive,updatedAt:Date.now()}); return{success:true,isActive:!p.isActive};',
  '  },',
  '});',
].join("\n"));

// dashboard.ts
write("src/convex/dashboard.ts", [
  'import { query } from "./_generated/server";',
  '',
  'export const getStats = query({',
  '  args: {}, handler: async (ctx) => {',
  '    const products = await ctx.db.query("products").collect();',
  '    const orders = await ctx.db.query("orders").collect();',
  '    const categories = await ctx.db.query("categories").collect();',
  '    const reviews = await ctx.db.query("reviews").collect();',
  '    return {',
  '      totalProducts: products.length,',
  '      kitchenProducts: products.filter(p=>p.businessType==="kitchen").length,',
  '      martProducts: products.filter(p=>p.businessType==="mart").length,',
  '      activeKitchenProducts: products.filter(p=>p.businessType==="kitchen"&&p.isActive).length,',
  '      activeMartProducts: products.filter(p=>p.businessType==="mart"&&p.isActive).length,',
  '      totalCategories: categories.length,',
  '      activeCategories: categories.filter(c=>c.isActive).length,',
  '      totalOrders: orders.length,',
  '      pendingOrders: orders.filter(o=>o.status==="pending").length,',
  '      preparingOrders: orders.filter(o=>o.status==="preparing").length,',
  '      deliveredOrders: orders.filter(o=>o.status==="delivered").length,',
  '      cancelledOrders: orders.filter(o=>o.status==="cancelled").length,',
  '      totalRevenue: orders.filter(o=>o.status==="delivered"&&o.paymentStatus==="paid").reduce((s,o)=>s+o.total,0),',
  '      pendingRevenue: orders.filter(o=>o.status!=="cancelled"&&o.paymentStatus==="pending").reduce((s,o)=>s+o.total,0),',
  '      totalReviews: reviews.length,',
  '      averageRating: reviews.length>0 ? Math.round((reviews.reduce((s,r)=>s+r.rating,0)/reviews.length)*10)/10 : 0,',
  '      recentOrders: orders.sort((a,b)=>b.createdAt-a.createdAt).slice(0,10).map(o=>({id:o._id,orderNumber:o.orderNumber,customerName:o.customerName,businessType:o.businessType,total:o.total,status:o.status,createdAt:o.createdAt})),',
  '      ordersByDay: (()=>{const now=Date.now();const r={};for(let i=0;i<7;i++){const d=new Date(now-i*86400000).toISOString().split("T")[0];r[d]=0;}for(const o of orders){if(o.createdAt>now-7*86400000){const d=new Date(o.createdAt).toISOString().split("T")[0];if(r[d]!==undefined)r[d]++;}}return Object.entries(r).sort(([a],[b])=>a.localeCompare(b)).map(([d,c])=>({date:d,count:c}));})(),',
  '      revenueByDay: (()=>{const now=Date.now();const r={};for(let i=0;i<7;i++){const d=new Date(now-i*86400000).toISOString().split("T")[0];r[d]=0;}for(const o of orders){if(o.status==="delivered"&&o.createdAt>now-7*86400000){const d=new Date(o.createdAt).toISOString().split("T")[0];if(r[d]!==undefined)r[d]+=o.total;}}return Object.entries(r).sort(([a],[b])=>a.localeCompare(b)).map(([d,rev])=>({date:d,revenue:rev}));})(),',
  '    };',
  '  },',
  '});',
  '',
  'export const getAlerts = query({ args: {}, handler: async (ctx) => {',
  '  const p=await ctx.db.query("products").collect();',
  '  return {lowStockCount:p.filter(x=>x.lowStockAlert&&x.stock<=x.lowStockAlert&&x.stock>0).length,outOfStockCount:p.filter(x=>x.isOutOfStock||x.stock<=0).length,totalAlerts:p.filter(x=>(x.lowStockAlert&&x.stock<=x.lowStockAlert&&x.stock>0)||x.isOutOfStock||x.stock<=0).length};',
  '}});',
].join("\n"));

// migration.ts
write("src/convex/migration.ts", [
  'import { v } from "convex/values";',
  'import { mutation, query } from "./_generated/server";',
  '',
  'export const getSummary = query({ args:{}, handler:async(ctx)=>{',
  '  const p=await ctx.db.query("products").collect(); const c=await ctx.db.query("categories").collect();',
  '  return {totalProducts:p.length,totalCategories:c.length,unassignedToCategory:p.filter(x=>!c.some(y=>y._id===x.categoryId)).length,kitchenProducts:p.filter(x=>x.businessType==="kitchen").length,martProducts:p.filter(x=>x.businessType==="mart").length};',
  '}});',
  '',
  'export const migrateProductsToCategory = mutation({',
  '  args:{productIds:v.array(v.id("products")),targetCategoryId:v.id("categories")},',
  '  handler:async(ctx,args)=>{',
  '    let m=0; for(const id of args.productIds){const p=await ctx.db.get(id);if(p&&p.categoryId!==args.targetCategoryId){await ctx.db.patch(id,{categoryId:args.targetCategoryId,updatedAt:Date.now()});m++;}}',
  '    return{success:true,message:`Migrated ${m} products`,migrated:m};',
  '  },',
  '});',
  '',
  'export const reassignBusinessType = mutation({',
  '  args:{productIds:v.array(v.id("products")),newBusinessType:v.union(v.literal("kitchen"),v.literal("mart"))},',
  '  handler:async(ctx,args)=>{let r=0;for(const id of args.productIds){const p=await ctx.db.get(id);if(p&&p.businessType!==args.newBusinessType){await ctx.db.patch(id,{businessType:args.newBusinessType,updatedAt:Date.now()});r++;}}return{success:true,message:`Reassigned ${r} products`};},',
  '});',
  '',
  'export const getOrphanedProducts = query({ args:{}, handler:async(ctx)=>{',
  '  const p=await ctx.db.query("products").collect(); const ids=new Set((await ctx.db.query("categories").collect()).map(c=>c._id));',
  '  return p.filter(x=>!ids.has(x.categoryId)).map(x=>({id:x._id,name:x.name}));',
  '}});',
  '',
  'export const deleteOrphanedProducts = mutation({ args:{productIds:v.array(v.id("products"))}, handler:async(ctx,args)=>{',
  '  for(const id of args.productIds) await ctx.db.delete(id);',
  '  return{success:true,message:`Deleted ${args.productIds.length} orphaned products`};',
  '}});',
].join("\n"));

// ─── 3. FRONTEND - UTILITIES ───
ensureDir("src/lib");
write("src/lib/weightUnits.ts", [
  'export const WEIGHT_UNITS = [',
  '  {value:"gm",label:"Gram",short:"gm"},',
  '  {value:"kg",label:"Kilogram",short:"kg"},',
  '  {value:"ml",label:"Millilitre",short:"ml"},',
  '  {value:"litre",label:"Litre",short:"litre"},',
  '  {value:"pcs",label:"Pieces",short:"pcs"},',
  '  {value:"piece",label:"Piece",short:"piece"},',
  '  {value:"plate",label:"Plate",short:"plate"},',
  '  {value:"pack",label:"Pack",short:"pack"},',
  '  {value:"box",label:"Box",short:"box"},',
  '  {value:"jar",label:"Jar",short:"jar"},',
  '  {value:"bottle",label:"Bottle",short:"bottle"},',
  "] as const;",
  "",
  'export function formatWeight(value: number, unit: string): string {',
  '  if(value<=0) return "";',
  '  switch(unit){',
  '    case"gm":return value>=1000?`${(value/1000).toFixed(0)} kg`:`${value} gm`;',
  '    case"ml":return value>=1000?`${(value/1000).toFixed(1)} litre`:`${value} ml`;',
  '    case"kg":return `${value} kg`;',
  '    case"litre":return `${value} litre`;',
  '    case"pcs":return `${value} pcs`;',
  '    case"piece":return `${value} piece${value!==1?"s":""}`;',
  '    case"plate":return `${value} plate${value!==1?"s":""}`;',
  '    case"pack":return `${value} pack${value!==1?"s":""}`;',
  '    case"box":return `${value} box${value!==1?"es":""}`;',
  '    case"jar":return `${value} jar${value!==1?"s":""}`;',
  '    case"bottle":return `${value} bottle${value!==1?"s":""}`;',
  '    default:return `${value} ${unit}`;',
  '  }',
  "}",
].join("\n"));

console.log("\nAll Phase 1 backend files written!");
